### ISSUE TITLE
[Task]: Update candy machine minted NFTs to new design

### ISSUE THREAD

**Issue by begonaalvarezd** [boxfish-studio/sugar-rush#103]
**Task description.**

Display minted NFTs grid
![image](https://user-images.githubusercontent.com/3624944/177521524-dde1dc59-aa9d-409b-88e9-efb25ad1230a.png)
![image](https://user-images.githubusercontent.com/3624944/177523191-71debdff-a623-494d-bd2d-2d420fd5b7bf.png)

**Requirements.**
- Create new NFT card component
- Display `loading...` while loading
- Display NFTs collection in a "grid" format with name & link to solscan
- Add x/y minted

**Comment by agus-xyz** [comment]
For simplicity and stability, and to save work for now, show only 10 nfts. We will add pagination later on.
