### ISSUE TITLE
[Task]: Update candy machine preview NFTs to new design

### ISSUE THREAD

**Issue by begonaalvarezd** [boxfish-studio/sugar-rush#104]
**Task description.**

![image](https://user-images.githubusercontent.com/3624944/177522045-847430a9-b6fc-45c6-a624-8305d90d47b0.png)

**Requirements.**
- Empty
- Cache loaded with NFTs grid and cache filename
- Loading status if necessary

**Comment by agus-xyz** [comment]
For simplicity and stability, and to save work for now, show only 10 nfts. We will add pagination later on.
