### ISSUE TITLE
[Task]: Create Solana Program to count how many CMs have been created

### ISSUE THREAD

**Issue by aspnxdd** [boxfish-studio/sugar-rush#13]

**Comment by agus-xyz** [comment]
what is this about??

**Comment by aspnxdd** [comment]
> what is this about??

I had the idea to create a solana program that has a counter which is increased by 1 everytime a CM is created in sugar-rush, then we can display this stat among possible others in a `/stats` page.

**Comment by begonaalvarezd** [comment]
Oh I see, a tracker to know how many CMs have been created with our app. Moved it to `backlog` as it is something we could do in the future. 

Thanks for the idea!
