### ISSUE TITLE
Hidden Settings case: No NFT from cache file

### ISSUE THREAD

**Issue by aspnxdd** [boxfish-studio/sugar-rush#175]
If hidden settings are active, NFT's cannot be previewed from the Cache file, since the items object is empty:
```json

{"program":{"uuid":"x","candyMachine":"xxxxxx","collection":"xxxxxx"},"items":{},"env":"mainnet-beta","cacheName":"syn-mainnet-beta-crew","startDate":"62d97800"}
```

Candy Machines without any item in the items object are most likely gonna be candy machines with Hidden Settings, therefore we should display a message justifying why no NFT from the cache file can be previewed -> because hiddenSettings are ON.

More info of the hidden settings [here](https://docs.metaplex.com/guides/archived/candy-machine-v2/configuration#hidden-settings)

**Comment by VmMad** [comment]
Fixed in [#170](https://github.com/boxfish-studio/sugar-rush/pull/170)
