### ISSUE TITLE
[Task]: Fix flashed sections on selected candy machine

### ISSUE THREAD

**Issue by begonaalvarezd** [boxfish-studio/sugar-rush#181]
When you select a candy machine, there is a flash of unminted NFTs that shouldnt be there

**Comment by begonaalvarezd** [comment]
I would appreciate being one of the reviewers of the PR linked to this task

**Comment by cpl121** [comment]
I can't reproduce this bug in the application @begonaalvarezd

**Comment by begonaalvarezd** [comment]
It doesnt happen anymore
