### ISSUE TITLE
[Task]: fix broken link to view candy machine in solscan

### ISSUE THREAD

**Issue by agus-xyz** [boxfish-studio/sugar-rush#98]
**Describe the bug**
The url to view CM in solscan seems broken. 

**To Reproduce**
Click on "view on solscan"
![image](https://user-images.githubusercontent.com/3696240/177509348-2f369d3f-5454-40b6-af78-1e32dea2b358.png)

**Expected behavior**
The url brings you to the cm account in solscan.

**Screenshots**
But it brings you here
![image](https://user-images.githubusercontent.com/3696240/177509535-47ca36fd-3440-4def-996a-d6905813c22f.png)

**Comment by cpl121** [comment]
Yes, solscan usually fails, we could change the links from `solscan.io` to the website that @aspnxdd  from `solana.fm` mentioned, what do you think?

**Comment by agus-xyz** [comment]
@cpl121 I am not 100% sure of this, but by testing a bit I found out a final `/` at the end of the url results in the url working 100% of times, while not adding the `/` results into the page not working sometimes 😵

**Comment by agus-xyz** [comment]
well... nope, that is not true either...

**Comment by agus-xyz** [comment]
if there is no way we can reliably show the address in solscan, but should find an alternative... thats shitty...

**Comment by cpl121** [comment]
We can add the two links, and if one fails, use the other
